name: Update version of all packages

on:
  push:
    branches:
      - main

permissions:  
  contents: write

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      srcChanged: ${{ steps.filter.outputs.src }}
      testChanged: ${{ steps.filter.outputs.test }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'
          test:
            - 'test/**'

  updateSrc:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.srcChanged == 'true'
    steps:
    - uses: actions/checkout@v3
    - name: workflow tests
      run: |
            echo "updateSrc"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git pull
            cd src
            npm version minor
            VERSION=$(node -p "require('./package.json').version")
            git commit -a -m "Update src ${VERSION}"
            git tag runtime-${VERSION}
            git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags

  updateTest:
    runs-on: ubuntu-latest
    needs: [paths-filter, updateSrc]
    if: ${{ always() && needs.paths-filter.outputs.testChanged == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: workflow tests
      run: |
            echo "updateTest"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git pull
            cd test
            npm version minor
            VERSION=$(node -p "require('./package.json').version")
            git commit -a -m "Update test ${VERSION}"
            git tag runtime-${VERSION}
            git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags

