# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update version of package

on:
  push:
    branches:
      - main
    paths:
      - src/**
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '16.x' ]

    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git config user.name "github-actions[bot]"
      - name: Update
        run: |
          cd src
          npm version minor
          VERSION=$(node -p "require('./package.json').version")
          git commit -a -m "Update src ${VERSION}"
          git tag runtime-${VERSION}
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags